// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TrueCoachAPI.Data;

namespace TrueCoachAPI.Migrations
{
    [DbContext(typeof(TrueCoachDbContext))]
    partial class TrueCoachDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TrueCoachAPI.Models.Exercise", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.Property<int>("WorkoutID");

                    b.HasKey("ID");

                    b.HasIndex("WorkoutID");

                    b.ToTable("Exercise");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Description = "Options for upper push will go here from the API side",
                            Name = "A. Upper Push",
                            WorkoutID = 1
                        },
                        new
                        {
                            ID = 2,
                            Description = "Options for upper pull will go here from the API side",
                            Name = "B. Upper Pull",
                            WorkoutID = 1
                        },
                        new
                        {
                            ID = 3,
                            Description = "Options for hiit will go here from the API side",
                            Name = "C. HIIT of choice for 30 seconds",
                            WorkoutID = 1
                        },
                        new
                        {
                            ID = 4,
                            Description = "Options for Horizontal push will go here from the API side",
                            Name = "A. Horizontal Push",
                            WorkoutID = 1
                        },
                        new
                        {
                            ID = 5,
                            Description = "Options for Horizontal pull will go here from the API side",
                            Name = "B. Horizontal pull",
                            WorkoutID = 1
                        },
                        new
                        {
                            ID = 6,
                            Description = "Options for Tricep will go here from the API side",
                            Name = "A. Tricep Variation",
                            WorkoutID = 1
                        },
                        new
                        {
                            ID = 7,
                            Description = "Options for Bicep will go here from the API side",
                            Name = "B. Bicep Variation",
                            WorkoutID = 1
                        });
                });

            modelBuilder.Entity("TrueCoachAPI.Models.User", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("UserName");

                    b.HasKey("ID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("TrueCoachAPI.Models.Workout", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("WorkoutGoals");

                    b.Property<int>("WorkoutTypeID");

                    b.HasKey("ID");

                    b.ToTable("Workout");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            WorkoutGoals = 2,
                            WorkoutTypeID = 1
                        },
                        new
                        {
                            ID = 2,
                            WorkoutGoals = 2,
                            WorkoutTypeID = 2
                        },
                        new
                        {
                            ID = 3,
                            WorkoutGoals = 2,
                            WorkoutTypeID = 3
                        },
                        new
                        {
                            ID = 4,
                            WorkoutGoals = 2,
                            WorkoutTypeID = 4
                        });
                });

            modelBuilder.Entity("TrueCoachAPI.Models.WorkoutType", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ExerciseID");

                    b.Property<string>("Name");

                    b.HasKey("ID");

                    b.HasIndex("ExerciseID");

                    b.ToTable("WorkoutType");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Name = "Upper Body"
                        },
                        new
                        {
                            ID = 2,
                            Name = "Lower Body"
                        },
                        new
                        {
                            ID = 3,
                            Name = "Full Body"
                        },
                        new
                        {
                            ID = 4,
                            Name = "Core"
                        });
                });

            modelBuilder.Entity("TrueCoachAPI.Models.Exercise", b =>
                {
                    b.HasOne("TrueCoachAPI.Models.Workout", "Workout")
                        .WithMany()
                        .HasForeignKey("WorkoutID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("TrueCoachAPI.Models.WorkoutType", b =>
                {
                    b.HasOne("TrueCoachAPI.Models.Exercise", "Exercise")
                        .WithMany()
                        .HasForeignKey("ExerciseID");
                });
#pragma warning restore 612, 618
        }
    }
}
